import 'package:get/get.dart';

class localstring extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Faham Community': 'Faham Community',
          'Become Our Members': 'Become Our Members',
          'PUBLISHED IN': 'PUBLISHED IN',
          'In': 'In',
          'Enter a valid email': 'Enter a valid email',
          'Please Wait....': 'Please Wait....',
          'Favorites': 'Favorites',
          'Create New Post': 'Create New Post',
          'Choose Profile photo': 'Choose Profile photo',
          'Home': 'Home',
          'Posts': 'Posts',
          'Members': 'Members',
          'Invite Friends': 'Invite Friends',
          'Language': 'Language',
          'English': 'English',
          'Pashto': 'Pashto',
          'Dari': 'Dari',
          'Dark Mood': 'Dark Mood',
          'Light Mood': 'Light Mood',
          'Privacy': 'Privacy',
          'Policy': 'Policy',
          'About Us': 'About Us',
          'Log Out': 'log Out',
          'Login': 'Login',
          'Sign up': 'Sign up',
          'Faham': 'Faham',
          'Public': 'public',
          'Sports': 'Sports',
          'Motivation': 'Motivation',
          'Health': 'Health',
          'Political': 'Political',
          'loves': 'loves',
          'Shares': 'Shares',
          'Views': 'Views',
          'Name': 'Name',
          'Enter Name:': 'Enter Name:',
          'password': 'password',
          'Movie': 'Movie',
          'Foods': 'Foods',
          'Religious': 'Religious',
          'Economic': 'Economic',
          'History': 'History',
          'Geographical': 'Geographical',
          'Do you have account?': 'Do you have account?',
          'Does not have account yet?': 'Does not have account yet?',
          'password': 'password',
          'Enter Password': 'Enter Password',
          'Sign Up Form': 'Sign Up Form',
          'First Name': 'First Name',
          'Enter First Name': 'Enter First Name',
          'last Name': 'last Name',
          'Enter Last Name:': 'Enter last Name:',
          'Email': 'Email',
          'Enter User Email:': 'Enter User Email:',
          'َBio': 'Bio',
          'Enter Your Biography:': 'Enter Your Biography:',
          'َJob': 'Job',
          'Enter Your Job:': 'Enter Your Job:',
          'َStatues': 'Statues',
          'Enter Your Statues:': 'Enter Your Statues:',
          'Confirm Password': 'Confirm password',
          'Camera': 'Camera',
          'Gallery': 'Gallery',
          'Sign Up': 'Sign Up',
          'Login In': 'Login In',
          'Log in Form ': 'Login in Form',
        },
        'pa_AF': {
          'Become Our Members': 'زمونږ ملګري شئ',
          'Privacy': 'امنیت',
          'Policy': 'تګلاره',
          'Faham Community': 'Faham Community',
          'PUBLISHED IN': 'خپور شوی په',
          'In': 'په',
          'Enter a valid email': 'صحي ایمیل ادرس داخیل کړئ',
          'Please Wait....': 'لږ صبر وکړئ',
          'Create New Post': 'نوې فوسټ وکړئ',
          'Log in Form ': 'داخلیدلو فورم',
          'Sign Up': 'نوی جوړول',
          'Login In': 'داخلیدل',
          'Camera': 'کېمره',
          'Gallery': 'ګالري',
          'Confirm Password': 'د پټ نوم صحی کول',
          'َStatues': 'حالت',
          'Enter Your Statues:': 'خپل حالت وليکئ',
          'َJob': 'دنده',
          'Enter Your Job:': 'خپله دنده ولیکئ',
          'َBio': 'پیژند',
          'Enter Your Biography:': 'خپل پیژند ولیکئ',
          'Email': 'ایمل ادرس',
          'Enter User Email:': 'ایمل ادرس داخیل کړئ',
          'last Name': 'اخر نوم',
          'Enter Last Name:': 'اخر نوم ولیکئ',
          'Enter First Name': 'لومړی نوم ولیکئ',
          'First Name': 'لومړی نوم',
          'Sign Up Form': 'د نوي اکونټ جوړیدلو فورم',
          'Enter Password': 'پټ نوم داخل کړئ',
          'password': 'پټ نوم',
          'Does not have account yet?': 'ایا اکونټ نلرئ؟',
          'Do you have account?': 'ایا اکونټ لرئ؟',
          'Choose Profile photo': 'خپل انځور غوره ګړئ',
          'Movie': 'سینما',
          'Foods': 'خوراک',
          'Religious': 'مذهب',
          'Economic': 'اقتصاد',
          'Historical': 'تاریخ',
          'Geographical': 'جغرافیه',
          'Enter Name:': 'خپل ایمیل ادرس وليکئ',
          'Favorites': 'په زړه پورې',
          'Posts': 'اعلانات',
          'Home': 'کور',
          'Members': 'استعمالونکي',
          'Invite Friends': 'ملګري دعوت کړئ',
          'Language': 'ژبې',
          'English': 'انګلش',
          'Pashto': 'پښتو',
          'Dari': ' دری',
          'Dark Mood': 'تیاره حالت',
          'Light Mood': 'روښانه حالت',
          'Help': 'مرسته',
          'FeedBack': 'بیا کتنه',
          'About Us': 'زمونږ په اړه',
          'Log Out': 'بهر کېدل',
          'Login': 'ننوتل',
          'Sign up': 'نوی جوړول',
          'Faham': 'فهم',
          'Public': 'عام',
          'Sports': 'لوبې',
          'Motivation': 'انګېزیشي',
          'Health': 'روغتیا',
          'Political': 'سیاست',
          'loves': 'خوښول',
          'Shares': 'خپرول',
          'Views': 'لیدل',
          'Name': 'نوم',
        },
        'dr_Af': {
          'Become Our Members': 'دوست ما شوید',
          'Privacy': 'امنیت',
          'Policy': 'روش',
          'Faham Community': 'Faham Community',
          'PUBLISHED IN': 'نشر شده در',
          'In': 'در',
          'Enter a valid email': 'ایمیل ادرس صحی دا وارید کنید',
          'Please Wait....': 'لطفاً صبور باشد',
          'Create New Post': 'فوست جدید کنید',
          'Log in Form ': 'فورم داخیل شدن',
          'Sign Up': 'نو ساختن',
          'Login In': 'داخل شدن',
          'Camera': 'کېمره',
          'Gallery': 'ګالري',
          'Confirm Password': 'تائید نام مخفی',
          'َStatues': 'حالت',
          'Enter Your Statues:': 'حالت خود را داخیل کنید',
          'َJob': 'وظیفه',
          'Enter Your Job:': 'وظیفه خود را داخیل کنید',
          'َBio': 'شهرت',
          'Enter Your Biography:': 'شهرت خود را داخیل کنید',
          'Email': 'ایمل ادرس',
          'Enter User Email:': 'ایمل ادرس را داخیل کنید',
          'last Name': 'نام اخر',
          'Enter Last Name:': 'نام اخر راداخل کنید',
          'Enter First Name': 'نام اول راداخل کنید',
          'First Name': 'نام اول',
          'Sign Up Form': 'فورم اکونت جدید',
          'Enter Password': 'نام مخفی خود را بنویسید',
          'password': 'نام مخفی',
          'Does not have account yet?': 'ایا اکونت ندارید؟',
          'Do you have account?': 'ايا اکونت دارید؟',
          'Choose Profile photo': 'تصویر خود را انتخاب کنید',
          'Movie': 'سینما',
          'Foods': 'خوارک',
          'Religious': 'مذهب',
          'Economic': 'اقتصاد',
          'Historical': 'تاریخ',
          'Geographical': 'جغرافيه',
          'Enter Name:': 'ایمیل ادرس خود رابنویسید',
          'Name': 'نام',
          'Favorites': 'انتخاب',
          'Home': 'خانه',
          'Members': 'استفاده کننده',
          'Invite Friends': 'دعوت رفیقان',
          'Language': 'زبان',
          'English': 'انګلش',
          'Posts': 'اعلانونه',
          'Pashto': 'پشتو',
          'Dari': 'دری',
          'Dark Mood': 'حالت تیارکی',
          'Light Mood': 'حالت روشنایی',
          'Help': 'کومک',
          'FeedBack': 'بازدید',
          'About Us': 'درباره ما',
          'Log Out': 'خارج شدن',
          'Login': 'داخل شدن',
          'Sign up': 'نوجورکردن',
          'Faham': 'فهم',
          'Public': 'عام',
          'Sports': 'ورزش',
          'Motivation': 'انګیزشي',
          'Health': 'صحت',
          'Political': 'سیاست',
          'loves': 'محبت',
          'Shares': 'شریک کردن',
          'Views': 'دیدن',
        }
      };
}
